In [5]:
import tensorflow as tf
import numpy as np

# Tensorflow datatype 
# 1. Constant 
# 2. Placeholder  
# 3. Variable

# Constant : 
# Data type for storing constants

# tf.constant(value, dtype=None, shape=None, name='Const')

In [1]:
# value : value of constant
# dtype : data type of constant
# shape : matrix dimension
# name : definition of the name of constant 

In [8]:
a = tf.constant([5], dtype=tf.float32)
print(a)

Tensor("Const_2:0", shape=(1,), dtype=float32)


In [10]:
sess = tf.Session()
sess.run(a)

array([5.], dtype=float32)

# matmul : 
# In order to multiply between matrices, multiply using the matmul function, not'*'

In [11]:
matrix1 = tf.constant([[1,2],[3,4]])  #shape(2,2)
matrix2 = tf.constant([[1],[3]])      #shape(2,1)

In [12]:
tf.matmul(matrix1, matrix2).eval(session=tf.Session())

array([[ 7],
       [15]], dtype=int32)

# reduce_mean : 
# Reduces when there are multiple values ​​in the matrix, averages according to the axis (= axis)

In [14]:
x = [[1.,2.],
      [3.,4.]]

In [15]:
a = tf.reduce_mean(x).eval(session = tf.Session())
print(a)

2.5


In [15]:
# reduce mean with axis=0
b = tf.(x, ).eval(session = tf.Session())
print(b)

[2. 3.]


In [17]:
# reduce mean with axis=1
c = tf.reduce_mean(x,axis=1).eval(session = tf.Session())
print(c)

[1.5 3.5]


# reduce_sum 

In [18]:
x = [[1,1,1],
     [1,1,1]]

In [20]:
# reduces all dimensions -> get the total sum
# [1+1+1+1+1+1=6]
# all dimensions are removed and only one scalar value is printed.
tf.reduce_sum(x).eval(session=sess)

6

In [22]:
# keepdims=True : keep the dimensions the same as the initial dimensions.
tf.reduce_sum(x, axis=0, keepdims=True).eval(session=sess)

array([[2, 2, 2]], dtype=int32)

In [23]:
tf.reduce_sum(x, axis=1, keepdims=True).eval(session=sess)

array([[3],
       [3]], dtype=int32)

In [24]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3, 3], dtype=int32)

# reshape : 
# It is used to change the shape of the tensor. If you put the desired value in the shape, it is adjusted to the corresponding shape

In [25]:
sess = tf.Session()

In [26]:
x = [i for i in range(10)]
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [28]:
# create 2-D matrix with n x 2
y =tf.reshape(x, shape=[-1,2]).eval(session=sess)
print(y)
print("y.shape:", y.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y.shape: (5, 2)


In [29]:
t = np.array(
    [[
        [0,1,2],
        [3,4,5]
    ],
        
        [
            [6,7,8],
            [9,10,11]
        ]
    ]
)

In [30]:
print(t.shape)

(2, 2, 3)


In [31]:
# 1-D matrix
z =tf.reshape(x, shape=[-1]).eval(session=sess)
print(z)
print("z.shape:", z.shape)

[0 1 2 3 4 5 6 7 8 9]
z.shape: (10,)


In [33]:
# if you enter -1 for shape, the fixed dimension is filled first, and the remaining part is automatically filled.
# create 2-D matrix with n x 3
z1 = tf.reshape(t, shape = [-1,3]).eval(session=sess)
print(z1)
print("z1.shape:", z1.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
z1.shape: (4, 3)


In [34]:
# create 3-D matrix with n x 1 x 3
z2 = tf.reshape(t, shape = [-1,1,3]).eval(session=sess)
print(z2)
print("z2.shape:", z2.shape)

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]
z2.shape: (4, 1, 3)


# squeeze :
# Delete a dimension of size 1 from tensor

In [35]:
x = np.array(
[
    [0],[1],[2]
]
)
print("x.shape:", x.shape) # 3,1

x.shape: (3, 1)


In [37]:
# find the size 1 of the dimensions and squeeze it out
y = tf.squeeze(x).eval(session=sess)
print(y)
print("y.shape:", y.shape)

[0 1 2]
y.shape: (3,)


# One hot Encoding : 
# Turning data into an array of 0s and 1s

In [35]:
tf.one_hot([[0],[1],[2]], depth=).eval(session=sess)

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]]], dtype=float32)

# Casting : 
# Change it to dtype. Mainly, it converts True and False to 0 and 1

In [36]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=tf.Session()))

[1 2 3 4]


In [37]:
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval(session=tf.Session()))

[1 0 1 0]


# stack : 
# Meaning of stacking in a stack structure 

In [39]:
x1 = [1,2]
x2 = [3,4]
x3 = [5,6]

In [40]:
y = tf.stack([x1,x2,x3],axis=0).eval(session=sess) # axis=0 -> row, axis=1 -> col
print(y)
print("y.shape:", y.shape)

[[1 2]
 [3 4]
 [5 6]]
y.shape: (3, 2)


# Ones and Zeros like : 
# Create a matrix filled with 0 or 1 for a given shape

In [38]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [41]:
print(tf.ones_like(x).eval(session=tf.Session())) # filled with 1

[[1]
 [1]
 [1]]


In [42]:
print(tf.zeros_like(x).eval(session=tf.Session())) # fille with 0

[[0]
 [0]
 [0]]


# argmax, argmin :
# It is used to get the index of the maximum value among the results obtained through softmax

In [44]:
x = [0,0,0,0,1]
tf.argmax(x).eval(session=sess)

4

In [45]:
# if the maximum value is more than 2, the result will be the earlier one
x = [5, 5, 4]
tf.argmax(x).eval(session=sess)

0

In [46]:
x = [0, 4, 1, 2]
tf.argmin(x).eval(session=sess)

0

In [47]:
x = [[2,4,6],
      [9,3,1]]

In [48]:
# max_index(2,9), max_index(4,3), max_index(6,1) -> [1,0,0]
tf.argmax(x,axis=0).eval(session=sess) # comparison in columns

array([1, 0, 0])

In [49]:
# max_index(2,3,4), max_index(9,3,1) -> [2,0]
tf.argmax(x,axis=1).eval(session=sess)

array([2, 0])